---
title: "vis_ii"
author: "ww2745"
date: "2024-10-13"
output: github_document
---

```{r setup}
library(tidyverse)
library(patchwork)
```

```{r}
weather_df = 
  read_csv("./data/weather_df.csv")

weather_df
```

## Remember this plot?
```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)
```

##labs
```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )
```

##Scales
```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )+
  scale_x_continuous(
    breaks=c(-15,0,15),
    labels=c("-15 C","0","15")
  )+
  scale_y_continuous(
    trans="sqrt",  #also could do "log" transformation
    position="right"
  )
```

let's look at color scales
```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )+
  scale_color_hue(
    name="Location", #change label name
    h=c(100,200))
``` 
use default color: recommended
```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE
  ) #default is continuous
``` 

##Themes 
Shift the legend.
```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE
  )+
  theme(legend.position="bottom")
``` 

Change the overall theme 
```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE
  )+
  theme_bw() 
``` 

minimal used by Jeff
```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE
  )+
  theme_minimal() 
``` 

```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE
  )+
  theme_classic() 
``` 

```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE
  )+
  ggthemes::theme_economist() 
``` 

themes will overwrite anything
```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE
  )+
  theme(legend.position="bottom")+
  theme_bw() 
``` 
to put legend at the bottom, we need to put bottom in the later line
```{r}
weather_df |> 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)+
  labs(
    title="Temperature plot",
    x="Minimum daily temperature(C)",
    y="Maximum daily temperature(C)",
    caption="Data from rnovaa package; temperatures in 2017."
  )+
  viridis::scale_color_viridis(
    name="Location",
    discrete=TRUE
  )+
  theme_bw()+
  theme(legend.position="bottom")
 
``` 

##Setting options
```{r}
library(tidyverse) 

knitr::opts_chunk$set(
  fig.width=6,
  fig.asp=.6,
  out.width="90%"
)

theme_set(theme_minimal()+theme(legend.position="bottom") )

options(
  ggplot2.continous.color="viridis",
  ggplot2.continous.fill="viridis"
)

scale_color_discrete=scale_color_viridis_d
scale_fill_discrete=scale_fill_viridis_d


  
```

